[package]
name = "machine-god-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "machine-god"
path = "src/main.rs"

[dependencies]
futures-core.workspace = true
machine-god-core.workspace = true
machine-god-native = { workspace = true, features = ["ai-gateway-http"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["signal"] }

[lints]
workspace = true
