[package]
name = "machine-god-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "machine-god"
path = "src/main.rs"

[dependencies]
machine-god-core = { path = "../machine-god-core" }
machine-god-native = { path = "../machine-god-native" }

[lints]
workspace = true

