[package]
name = "machine-god-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = []
ai-gateway-http = [
    "dep:bytes",
    "dep:hyper",
    "dep:reqwest",
    "dep:rustls",
    "dep:tokio",
    "dep:webpki-root-certs",
]

[dependencies]
futures-core.workspace = true
machine-god-core.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bytes = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
webpki-root-certs = { workspace = true, optional = true }

[target.'cfg(unix)'.dependencies]
libc.workspace = true
rustix.workspace = true

[dev-dependencies]
futures-executor = "0.3.31"
futures-util = "0.3.31"
machine-god-testkit = { version = "0.1.0", path = "../machine-god-testkit" }

[lints]
workspace = true
